apiVersion: v1
kind: Service
metadata:
  name: daf-semantic-validator
  labels:
    app: daf-semantic-validator
spec:
  ports:
  - port: 9000
  selector:
    app: daf-semantic-validator
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: daf-semantic-validator-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: daf-semantic-validator
    spec:
      imagePullSecrets:
        - name: regsecret
      containers:
        - name: daf-semantic-validator
          image: nexus.daf.teamdigitale.it/daf-semantic-validator:1.0.1
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: glusterfsvol
              readOnly: false
              mountPath: /data
              subPath: daf-semantic-validator
      volumes:
          - name: glusterfsvol
            persistentVolumeClaim:
              claimName: gluster-claim
